### ISSUE TITLE
Signup response as []

### ISSUE THREAD

**Issue by prakashadabala1** [bravegurkha/qube#38]
POST /api/signup HTTP/1.1
Host: qubedev.qubenow.com
Cache-Control: no-cache
Postman-Token: b581c080-e7e2-8b26-9c23-60241b83eee6
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

vsprakash.ios@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

password123
------WebKitFormBoundary7MA4YWxkTrZu0gW--

**Response**
[]

When i tried with same email and password. I am getting this 

When i tried second time 

{
  "success": false,
  "error": {
    "email": [
      "The email has already been taken."
    ]
  },
  "error_code": 400
}

Here when error message should be like this. Please change all error message formats to this format. Let me know if any doubts.

{
  "success": false,
  "error":  "The email has already been taken.",
  "error_code": 400
}

**Comment by swornim00** [comment]
Now Signup will return token if the sign is successful 😄

**Comment by bravegurkha** [comment]
Now Signup will return token if the sign is successful 😄
