### ISSUE TITLE
user/me getting issue

### ISSUE THREAD

**Issue by prakashadabala1** [bravegurkha/qube#40]
qubedev.qubenow.com/api/user/me?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjM1LCJpc3MiOiJodHRwOlwvXC9xdWJlZGV2LnF1YmVub3cuY29tXC9hcGlcL2F1dGgiLCJpYXQiOjE0ODEyNTkzMDQsImV4cCI6MTU0MTI1OTMwNCwibmJmIjoxNDgxMjU5MzA0LCJqdGkiOiI4ZWI5NzQ0OTU1MGZiZTYxOWMzODM4YWE4MmU4NGQ2MyJ9._cl-rzQH3SSl4Tf99mh2Uq7kMhgN5EhJp5Lf_QUCZOQ
![screen shot 2016-12-09 at 10 30 46 am](https://cloud.githubusercontent.com/assets/23737740/21038244/176f2036-bdfa-11e6-8deb-d08339113df6.png)

**Comment by swornim00** [comment]
Use GET Not POST.
