### ISSUE TITLE
/api/users/near user should access without token

### ISSUE THREAD

**Issue by prakashadabala1** [bravegurkha/qube#41]
user should pass lat and long with this api then user should get near by users. User should not have access token.
Near Users:
Request Type: GET
Request URL: /api/users/near
Parameters : none
Returns: array user data

**Comment by swornim00** [comment]
Why would you want users near with out access token? Why would you want anyone to find near users? If you still want then We can add a parameter as id .

**Comment by prakashadabala1** [comment]
user should able to access other users even they dont have registered. So the user needs find near by users without authentication. And also user details too. Dont need authentication. If they need to do some action like follow, like , message. they need to authenticate.

**Comment by swornim00** [comment]
Sure.. I will be doing it.

**Comment by swornim00** [comment]
Fixed with #45
