### ISSUE TITLE
/api/user/follower issue

### ISSUE THREAD

**Issue by prakashadabala1** [bravegurkha/qube#42]
Passed 
POST /api/user/follower?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjM1LCJpc3MiOiJodHRwOlwvXC9xdWJlZGV2LnF1YmVub3cuY29tXC9hcGlcL2F1dGgiLCJpYXQiOjE0ODEyNTkzMDQsImV4cCI6MTU0MTI1OTMwNCwibmJmIjoxNDgxMjU5MzA0LCJqdGkiOiI4ZWI5NzQ0OTU1MGZiZTYxOWMzODM4YWE4MmU4NGQ2MyJ9._cl-rzQH3SSl4Tf99mh2Uq7kMhgN5EhJp5Lf_QUCZOQ HTTP/1.1
Host: qubedev.qubenow.com
Cache-Control: no-cache
Postman-Token: 4b35a3d9-28be-d06f-f4f6-d502915140a1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

35
------WebKitFormBoundary7MA4YWxkTrZu0gW--

Get Followers
Request Type: GET
Request URL: /api/user/follower
Parameters : {‘id’}
Returns: success  or error
![screen shot 2016-12-09 at 10 53 20 am](https://cloud.githubusercontent.com/assets/23737740/21038620/4142d4a4-bdfd-11e6-9e53-9ef73ef5bf85.png)

**Comment by swornim00** [comment]
It is not follower, it is followers. I will update the doc.
