### ISSUE TITLE
/api/user/followed issue

### ISSUE THREAD

**Issue by prakashadabala1** [bravegurkha/qube#43]
POST /api/user/followed?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjM1LCJpc3MiOiJodHRwOlwvXC9xdWJlZGV2LnF1YmVub3cuY29tXC9hcGlcL2F1dGgiLCJpYXQiOjE0ODEyNTkzMDQsImV4cCI6MTU0MTI1OTMwNCwibmJmIjoxNDgxMjU5MzA0LCJqdGkiOiI4ZWI5NzQ0OTU1MGZiZTYxOWMzODM4YWE4MmU4NGQ2MyJ9._cl-rzQH3SSl4Tf99mh2Uq7kMhgN5EhJp5Lf_QUCZOQ HTTP/1.1
Host: qubedev.qubenow.com
Cache-Control: no-cache
Postman-Token: 26f7bddd-8486-0694-2c8d-47510b9c0a29
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

35
------WebKitFormBoundary7MA4YWxkTrZu0gW--
![screen shot 2016-12-09 at 10 55 19 am](https://cloud.githubusercontent.com/assets/23737740/21038651/81e2481e-bdfd-11e6-8e3f-41ca8a450602.png)

**Comment by swornim00** [comment]
USE GET Not POST
